# -*- coding: utf-8 -*-
"""EMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nwn6j3ailgxwtXh6GExofs53CTTpXOwU
"""

employees = {
    101: {"name": "Satya", "age": 27, "department": "HR", "salary": 50000}
}

def add_employee():
    while True:
        emp_id = int(input("Enter Employee ID: "))

        if emp_id in employees:
            print("Employee ID already exists. Try again.")
        else:
            break

    name = input("Enter Name: ")
    age = int(input("Enter Age: "))
    department = input("Enter Department: ")
    salary = int(input("Enter Salary: "))

    employees[emp_id] = {
        "name": name,
        "age": age,
        "department": department,
        "salary": salary
    }

    print("Employee added successfully!\n")

def view_employees():
    if not employees:
        print("No employees available.\n")
        return

    print("\n--- Employee List ---")
    print("ID\tName\tAge\tDepartment\tSalary")

    for emp_id, details in employees.items():
        print(f"{emp_id}\t{details['name']}\t{details['age']}\t{details['department']}\t{details['salary']}")

    print()

def search_employee():
    emp_id = int(input("Enter Employee ID to search: "))

    if emp_id in employees:
        emp = employees[emp_id]
        print("\nEmployee Found:")
        print(f"Name: {emp['name']}")
        print(f"Age: {emp['age']}")
        print(f"Department: {emp['department']}")
        print(f"Salary: {emp['salary']}\n")
    else:
        print("Employee not found.\n")

def main_menu():
    while True:
        print("===== Employee Management System =====")
        print("1. Add Employee")
        print("2. View All Employees")
        print("3. Search Employee")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            add_employee()
        elif choice == "2":
            view_employees()
        elif choice == "3":
            search_employee()
        elif choice == "4":
            print("Thank you for using EMS!")
            break
        else:
            print("Invalid choice. Try again.\n")

main_menu()